#!/usr/bin/env node
/**
 * generate_sitemap.js
 * -------------------
 * Reads  : website/data/movies.json
 * Writes : website/sitemap.xml
 *          website/robots.txt
 *
 * Usage  : node scripts/generate_sitemap.js
 * Env    : SITE_BASE_URL  (default: https://yoursite.lk)
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Config ──────────────────────────────────────────────────────────────────
const BASE_URL    = (process.env.SITE_BASE_URL || 'https://yoursite.lk').replace(/\/$/, '');
const ROOT        = path.resolve(__dirname, '..');
const MOVIES_JSON = path.join(ROOT, 'website', 'data', 'movies.json');
const SITEMAP_OUT = path.join(ROOT, 'website', 'sitemap.xml');
const ROBOTS_OUT  = path.join(ROOT, 'website', 'robots.txt');

// ── Helpers ──────────────────────────────────────────────────────────────────
function escapeXml(str) {
  return String(str)
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
    .replace(/'/g,  '&apos;');
}

function toW3CDate(value) {
  if (!value) return new Date().toISOString().slice(0, 10);
  const d = new Date(value);
  return isNaN(d.getTime()) ? new Date().toISOString().slice(0, 10) : d.toISOString().slice(0, 10);
}

function urlEntry(loc, lastmod, changefreq, priority) {
  return [
    '  <url>',
    `    <loc>${escapeXml(loc)}</loc>`,
    `    <lastmod>${lastmod}</lastmod>`,
    `    <changefreq>${changefreq}</changefreq>`,
    `    <priority>${priority.toFixed(1)}</priority>`,
    '  </url>',
  ].join('\n');
}

// ── Load movies.json ─────────────────────────────────────────────────────────
let movies = [];
if (fs.existsSync(MOVIES_JSON)) {
  try {
    const raw    = fs.readFileSync(MOVIES_JSON, 'utf8');
    const parsed = JSON.parse(raw);
    movies = Array.isArray(parsed) ? parsed : (parsed.movies || []);
    console.log(`✅  Loaded ${movies.length} movies from movies.json`);
  } catch (err) {
    console.error('❌  Failed to parse movies.json:', err.message);
    process.exit(1);
  }
} else {
  console.warn('⚠️   movies.json not found – generating sitemap with static pages only.');
}

// ── Static pages ─────────────────────────────────────────────────────────────
const today = new Date().toISOString().slice(0, 10);

const staticPages = [
  { loc: `${BASE_URL}/`,            lastmod: today, changefreq: 'daily',   priority: 1.0 },
  { loc: `${BASE_URL}/search.html`, lastmod: today, changefreq: 'weekly',  priority: 0.8 },
  { loc: `${BASE_URL}/genres.html`, lastmod: today, changefreq: 'weekly',  priority: 0.7 },
  { loc: `${BASE_URL}/about.html`,  lastmod: today, changefreq: 'monthly', priority: 0.4 },
];

// ── Build movie URL entries ───────────────────────────────────────────────────
const movieEntries = movies.map((movie) => {
  const slug = movie.slug
    || (movie.title || movie.name || 'unknown')
        .toLowerCase()
        .trim()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-');

  const loc      = `${BASE_URL}/movie.html?id=${encodeURIComponent(slug)}`;
  const lastmod  = toW3CDate(movie.added_at || movie.created_at || movie.date);
  const priority = movie.featured ? 0.9 : 0.8;
  return urlEntry(loc, lastmod, 'weekly', priority);
});

// ── Assemble sitemap ──────────────────────────────────────────────────────────
const staticEntries = staticPages.map(p =>
  urlEntry(p.loc, p.lastmod, p.changefreq, p.priority)
);

const xmlLines = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!--',
  '  sitemap.xml – AUTO-GENERATED by scripts/generate_sitemap.js',
  `  Last updated : ${new Date().toISOString()}`,
  `  Total URLs   : ${staticEntries.length + movieEntries.length}`,
  '  DO NOT edit manually – changes will be overwritten on next deploy.',
  '-->',
  '<urlset',
  '  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
  '  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
  '  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9',
  '    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">',
  '',
  '  <!-- ═══════════ Static pages ═══════════ -->',
  ...staticEntries,
  '',
  `  <!-- ═══════════ Movie pages (${movieEntries.length} total) ═══════════ -->`,
  ...movieEntries,
  '',
  '</urlset>',
];

fs.writeFileSync(SITEMAP_OUT, xmlLines.join('\n'), 'utf8');
console.log(`✅  sitemap.xml  → ${SITEMAP_OUT}`);
console.log(`    Static : ${staticEntries.length}  |  Movies : ${movieEntries.length}  |  Total : ${staticEntries.length + movieEntries.length}`);

// ── Generate robots.txt ───────────────────────────────────────────────────────
const robotsTxt = `# robots.txt – generated by scripts/generate_sitemap.js
# Last updated: ${new Date().toISOString()}

# ── Allow major search engines ─────────────────────────────────
User-agent: Googlebot
Allow: /
Crawl-delay: 2

User-agent: Googlebot-Image
Allow: /
Crawl-delay: 5

User-agent: Bingbot
Allow: /
Crawl-delay: 5

User-agent: Slurp
Allow: /
Crawl-delay: 10

User-agent: DuckDuckBot
Allow: /
Crawl-delay: 5

# ── Generic rule for all other bots ────────────────────────────
User-agent: *
Allow: /

# Disallow admin / internal paths
Disallow: /admin/
Disallow: /api/
Disallow: /tmp/
Disallow: /.git/
Disallow: /scripts/
Disallow: /node_modules/
Disallow: /.env
Disallow: /.github/

# Disallow duplicate/low-quality query pages
Disallow: /*?page=
Disallow: /*?sort=
Disallow: /*?ref=
Disallow: /*?utm_

# Block known aggressive scrapers
User-agent: AhrefsBot
Disallow: /

User-agent: SemrushBot
Disallow: /

User-agent: MJ12bot
Disallow: /

# ── Sitemap location ─────────────────────────────────────────────
Sitemap: ${BASE_URL}/sitemap.xml

# ── Canonical host ───────────────────────────────────────────────
Host: ${BASE_URL.replace(/^https?:\/\//, '')}
`;

fs.writeFileSync(ROBOTS_OUT, robotsTxt, 'utf8');
console.log(`✅  robots.txt   → ${ROBOTS_OUT}`);
